# Generated by Django 5.2.7 on 2025-10-17 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='hora_chegada',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 17, 23, 52, 21, 735982, tzinfo=datetime.timezone.utc)),
        ),
    ]
