# Generated by Django 5.2.7 on 2025-10-20 22:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_pessoa_atendido_pessoa_hora_chegada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='hora_chegada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
